version: '2'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/redis

    toxpro:
        build: .
        ports:
            - "5000:5000"
        image: toxpro
        volumes:
            - ./instance/:/home/toxpro/instance
        entrypoint: ["./boot.sh"]
        stdin_open: true
        tty: true

    worker:
        image: toxpro
        depends_on:
            - redis
            - toxpro
        entrypoint: ["./boot_worker.sh"]
        volumes:
            - ./instance/:/home/toxpro/instance

# this is necessary for the workers to
# share writing to the SQLite I believ
volumes:
  instance_vol:
